name: ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          os: ${{ matrix.os}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e ./humanDigitalTwin/stereotypes
          if [ -f ./**/*requirements.txt ]; then pip install -r ./**/*requirements.txt; fi
      - name: Create mongo Docker container
        uses: ankane/setup-mongodb@v1
      - name: Start Redis
        uses: supercharge/redis-github-action@1.5.0
        with:
          redis-version: 5
      - name: Set up RabbitMQ
        run: |
          docker pull rabbitmq:3-management
          docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management
          sleep 10  # Give some time for RabbitMQ to start
      - name: Test with pytest
        run: |
          pytest -v --cov || pytest -v --cov || pytest -v --cov
